build:
  build_starting:
    image: python:2
    commands:
      - echo "Beginning new build"
    run_tests:
        image: python:2-alpine
        commands:
            - pip install -r roomfinder_web/requirements.txt
            - python testing.py
