pipeline:
  build:
    image: python:2-alpine
    environment:
      - roomfinder_dispo_server=http://37.187.22.103:5002
      - roomfinder_data_server=http://37.187.22.103:5001
      - roomfinder_spark_bot_email=roomfinder-dev@sparkbot.io
      - spark_token=***REMOVED***
      - roomfinder_spark_bot_url=http://37.187.22.103:6666
      - log_room_id=***REMOVED***
    commands:
      - echo "Beginning new build"
      - pip install -r roomfinder_spark/requirements.txt
      - python testing.py
  publish:
    image: plugins/docker
    repo: guismo/roomfinder_spark
    tag: [ latest ]
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: push

  # notify:
  #     spark:
  #         image: hpreston/drone-spark
  #         auth_token: ***REMOVED***
  #         roomId: ***REMOVED***

